export const Datas = [
    {
      roomnum: 1,
      firstNFT: "",
      secondNFT: "",
      firstaddress: "",
      secondaddress: "",
      firstrandom: 0,
      secondrandom: 0,
      tokenId: 0,
      fightroom: 0,
      whichfight: 0,
    },
    {
      roomnum: 2,
      firstNFT: "",
      secondNFT: "",
      firstaddress: "",
      secondaddress: "",
      firstrandom: 0,
      secondrandom: 0,
      tokenId: 0,
      fightroom: 0,
      whichfight: 0,
    },
    {
      roomnum: 3,
      firstNFT: "",
      secondNFT: "",
      firstaddress: "",
      secondaddress: "",
      firstrandom: 0,
      secondrandom: 0,
      tokenId: 0,
      whichfight: 0,
      fightroom: 0,
    },
    {
      roomnum: 4,
      firstNFT: "",
      secondNFT: "",
      firstaddress: "",
      secondaddress: "",
      firstrandom: 0,
      secondrandom: 0,
      tokenId: 0,
      fightroom: 0,
      whichfight: 0,
    },
    {
      roomnum: 5,
      firstNFT: "",
      secondNFT: "",
      firstaddress: "",
      secondaddress: "",
      firstrandom: 0,
      secondrandom: 0,
      tokenId: 0,
      fightroom: 0,
      whichfight: 0,
    },
    {
      roomnum: 6,
      firstNFT: "",
      secondNFT: "",
      firstaddress: "",
      secondaddress: "",
      firstrandom: 0,
      secondrandom: 0,
      tokenId: 0,
      fightroom: 0,
      whichfight: 0,
    },
    {
      roomnum: 7,
      firstNFT: "",
      secondNFT: "",
      firstaddress: "",
      secondaddress: "",
      firstrandom: 0,
      secondrandom: 0,
      tokenId: 0,
      fightroom: 0,
      whichfight: 0,
    },
    {
      roomnum: 8,
      firstNFT: "",
      secondNFT: "",
      firstaddress: "",
      secondaddress: "",
      firstrandom: 0,
      secondrandom: 0,
      tokenId: 0,
      fightroom: 0,
      whichfight: 0,
    },
  ];